version: '3.8'

services:
  football-bot:
    build: .
    container_name: football-betting-bot
    restart: unless-stopped
    environment:
      - ODDS_API_KEY=${ODDS_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
